### ISSUE TITLE
This application did not respond

### ISSUE THREAD

**Issue by OS9-boop** [xdnw/locutus#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

[**Screenshots**](url
![Screenshot_20241011-145825_Discord](https://github.com/user-attachments/assets/c678d907-e400-4b82-b123-d985fe6d8e1b)
) i am trying to register byt it shows the application did not respond 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xdnw** [comment]
Try again. The bot was offline earlier.
