### ISSUE TITLE
Switch license from GPL to AGPL

### ISSUE THREAD

**Issue by pythonian23** [xdnw/locutus#7]
**Is your feature request related to a problem? Please describe.**
The GNU Affero General Public License fits this project better than the plain GPL.

**Describe the solution you'd like**
It is extremely unlikely for locutus to be directly distributed, but instead would most likely be run over a network. The GNU General Public License does not account for this, and its terms may not apply to such cases.

**Comment by SimonePY** [comment]
Hey @pythonian23 ,
Thanks for reporting this, it will be discussed and in case changed at the next commit!
